version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password" # Đặt mật khẩu cho người dùng sa
    ports:
      - "8000:8000"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
