version: '3.4'

services:
  projectcnpmdjango:
    image: projectcnpmdjango
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 Djangovenv/SunDental/manage.py runserver 0.0.0.0:9000 --nothreading --noreload"]
    ports:
      - 9000:9000
      - 5678:5678
