# Generated by Django 5.0.11 on 2025-02-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_time',
            field=models.CharField(max_length=25),
        ),
    ]
