# Generated by Django 5.0.11 on 2025-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('dentist', 'Dentist'), ('clinic_owner', 'Clinic Owner'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
