# Generated by Django 5.0.11 on 2025-02-19 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(choices=[('SANG', 'Ca Sáng (7:00 - 11:00)'), ('CHIEU', 'Ca Chiều (13:00 - 17:00)'), ('TOI', 'Ca Tối (18:00 - 22:00)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(verbose_name='Ngày làm việc')),
                ('thu', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Thứ')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Còn hoạt động')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ')),
                ('ca_lam', models.ManyToManyField(to='E_Manage.calamviec', verbose_name='Ca làm việc')),
            ],
            options={
                'verbose_name': 'Lịch làm việc',
                'verbose_name_plural': 'Lịch làm việc',
                'ordering': ['thu', 'ngay'],
                'unique_together': {('bac_si', 'ngay')},
            },
        ),
    ]
