# Generated by Django 5.0.11 on 2025-02-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='Dental_branch',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='FullName',
            new_name='FName',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='License_number',
            new_name='Lnumber',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='Phone_Number',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='Specialization',
            new_name='Spec',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='Email',
            new_name='email',
        ),
    ]
