# Generated by Django 5.0.12 on 2025-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0002_auto_20250212_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Schedule',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('Specialty_Name', models.CharField(max_length=255)),
                ('Work_Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
        ),
    ]
