# Generated by Django 5.0.11 on 2025-02-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
