# Generated by Django 5.0.11 on 2025-02-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0002_rename_dental_branch_dentist_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentist',
            old_name='Branch',
            new_name='Dental_branch',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='FName',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='Lnumber',
            new_name='License_number',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='PhoneNumber',
            new_name='Phone_Number',
        ),
        migrations.RenameField(
            model_name='dentist',
            old_name='Spec',
            new_name='Specialization',
        ),
    ]
