# Generated by Django 5.0.11 on 2025-02-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0002_alter_doctorschedule_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày làm việc')),
                ('shift', models.CharField(choices=[('sang', 'Sáng'), ('chieu', 'Chiều'), ('toi', 'Tối'), ('ca_ngay', 'Cả ngày')], max_length=10, verbose_name='Ca làm')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Manage.dentist', verbose_name='Nha sĩ')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
