# Generated by Django 5.0.11 on 2025-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0003_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chi_nhanh',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='chuyen_nganh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
