# Generated by Django 5.0.11 on 2025-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0003_alter_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangKiLichNghi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ngay_nghi', models.DateField(blank=True, null=True)),
                ('ca_nghi', models.CharField(blank=True, max_length=50, null=True)),
                ('ly_do_nghi', models.CharField(blank=True, max_length=255, null=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
