# Generated by Django 5.0.11 on 2025-02-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0003_dentist_dental_branch_dentist_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='Birthday',
        ),
        migrations.RemoveField(
            model_name='dentist',
            name='Gender',
        ),
        migrations.AddField(
            model_name='dentist',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AddField(
            model_name='dentist',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=1, null=True),
        ),
    ]
