# Generated by Django 5.0.11 on 2025-02-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0003_lichlam_delete_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(choices=[('SANG', 'Ca Sáng (7:00 - 11:00)'), ('CHIEU', 'Ca Chiều (13:00 - 17:00)'), ('TOI', 'Ca Tối (18:00 - 22:00)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('thu', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')])),
                ('trang_thai', models.BooleanField(default=True)),
                ('bac_si', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ca_lam', models.ManyToManyField(to='E_Manage.calamviec')),
            ],
            options={
                'ordering': ['ngay', 'thu'],
                'unique_together': {('bac_si', 'ngay')},
            },
        ),
        migrations.DeleteModel(
            name='LichLam',
        ),
    ]
