# Generated by Django 5.0.11 on 2025-02-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0004_dangkilichnghi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='Dental_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
