# Generated by Django 5.0.11 on 2025-02-19 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0004_calamviec_lichlamviec_delete_lichlam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lichlamviec',
            options={'ordering': ['thu', 'ngay'], 'verbose_name': 'Lịch làm việc', 'verbose_name_plural': 'Lịch làm việc'},
        ),
        migrations.AddField(
            model_name='lichlamviec',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='bac_si',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bác sĩ'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='ca_lam',
            field=models.ManyToManyField(to='E_Manage.calamviec', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='ngay',
            field=models.DateField(verbose_name='Ngày làm việc'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='thu',
            field=models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], verbose_name='Thứ'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Còn hoạt động'),
        ),
    ]
