# Generated by Django 5.0.11 on 2025-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0004_commentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentform',
            name='message',
            field=models.TextField(),
        ),
    ]
