# Generated by Django 5.0.11 on 2025-02-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0005_dentist_dental_branch_dentist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
