# Generated by Django 5.0.11 on 2025-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0005_alter_commentform_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=255)),
                ('License_number', models.CharField(max_length=50)),
                ('Birthday', models.DateField()),
                ('Gender', models.BooleanField()),
            ],
        ),
    ]
