# Generated by Django 5.0.11 on 2025-02-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0005_customuser_image_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='img/avt/default_male.png', upload_to='img/avt/'),
        ),
    ]
