# Generated by Django 5.0.11 on 2025-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentist',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/avt/'),
        ),
    ]
