# Generated by Django 5.0.11 on 2025-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0006_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
