# Generated by Django 5.0.11 on 2025-02-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0007_services_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
