# Generated by Django 5.0.11 on 2025-02-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0007_services_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('Specialty_Name', models.CharField(max_length=255)),
                ('Work_Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
            ],
        ),
    ]
