# Generated by Django 5.0.11 on 2025-02-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0010_lichhen_nhacnho'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lichhen',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='nhacnho',
            new_name='Reminder',
        ),
    ]
