# Generated by Django 5.0.11 on 2025-02-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0011_rename_lichhen_appointment_rename_nhacnho_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=100),
        ),
    ]
