# Generated by Django 5.0.11 on 2025-02-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0013_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(choices=[('02 Võ Oanh, Phường 25, Bình Thạnh, Hồ Chí Minh', '02 Võ Oanh, Phường 25, Bình Thạnh, Hồ Chí Minh'), ('70 Tô Ký, Tân Chánh Hiệp, Quận 12, TPHCM', '70 Tô Ký, Tân Chánh Hiệp, Quận 12, TPHCM'), ('10/12 Trần Não, KP3, P. Bình An, TP. Thủ Đức, TP. HCM', '10/12 Trần Não, KP3, P. Bình An, TP. Thủ Đức, TP. HCM')], max_length=255)),
                ('service', models.CharField(choices=[('nho_rang', 'Nhổ răng'), ('han_rang', 'Hàn răng'), ('dieu_tri_tuy', 'Điều trị tủy'), ('nieng_rang_kim_loai', 'Niềng răng kim loại'), ('nieng_rang_trong_suot', 'Niềng răng trong suốt'), ('dieu_tri_lech_khop_can', 'Điều trị lệch khớp cắn'), ('lam_rang_su', 'Làm răng sứ'), ('cay_ghep_implant', 'Cấy ghép Implant'), ('mat_dan_su_veneer', 'Mặt dán sứ Veneer'), ('cao_voi_rang', 'Cạo vôi răng'), ('dieu_tri_viem_nuou', 'Điều trị viêm nướu'), ('ghep_nuou', 'Ghép nướu'), ('lay_cao_rang_sau', 'Lấy cao răng sâu dưới nướu'), ('dieu_tri_ap_xe_rang', 'Điều trị áp xe răng'), ('tai_tao_xuong_o_rang', 'Tái tạo xương ổ răng'), ('kham_dinh_ky', 'Khám sức khỏe răng miệng định kỳ'), ('chup_x_quang_toan_ham', 'Chụp X-quang răng toàn hàm'), ('tu_van_ke_hoach_dieu_tri', 'Tư vấn kế hoạch điều trị'), ('chup_ct_cone_beam_3d', 'Chụp CT Cone Beam 3D'), ('do_khop_can_ky_thuat_so', 'Đo khớp cắn kỹ thuật số'), ('chup_phim_panorama', 'Chụp phim Panorama'), ('tay_trang_bang_laser', 'Tẩy trắng răng bằng công nghệ Laser'), ('tu_van_dinh_duong', 'Tư vấn dinh dưỡng và phòng ngừa bệnh lý răng miệng'), ('danh_gia_suc_khoe_rang_mieng', 'Đánh giá sức khỏe răng miệng chuyên sâu')], max_length=50)),
                ('day_appointment', models.DateField(max_length=10)),
                ('time_appointment', models.CharField(choices=[('08:00', '08:00 AM'), ('08:45', '08:45 AM'), ('09:30', '09:30 AM'), ('10:15', '10:15 AM'), ('11:00', '11:00 AM'), ('11:45', '11:45 AM'), ('13:15', '01:15 PM'), ('14:00', '02:00 PM'), ('14:45', '02:45 PM'), ('15:30', '03:30 PM'), ('16:15', '04:15 PM')], max_length=5)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='booking_images/')),
            ],
        ),
    ]
