# Generated by Django 5.0.11 on 2025-02-13 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0016_gio_hang_delete_giohang'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('dich_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Manage.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Gio_Hang',
        ),
    ]
