# Generated by Django 5.0.11 on 2025-02-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0017_giohang_delete_gio_hang'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
