# Generated by Django 5.0.11 on 2025-02-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0018_services_info_services_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField()),
                ('ongoing', models.IntegerField()),
                ('not_started', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_count', models.IntegerField()),
            ],
        ),
    ]
