# Generated by Django 5.0.11 on 2025-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0019_treatmentprogress_treatmentschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentProgress',
        ),
        migrations.DeleteModel(
            name='TreatmentSchedule',
        ),
        migrations.AddField(
            model_name='customuser',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='not_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ongoing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='session_count',
            field=models.IntegerField(default=0),
        ),
    ]
