# Generated by Django 5.0.11 on 2025-02-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0020_delete_treatmentprogress_delete_treatmentschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='not_started',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='session_count',
        ),
    ]
