# Generated by Django 5.0.11 on 2025-02-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='Phone_Number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
