# Generated by Django 5.0.11 on 2025-02-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Manage', '0002_alter_dentist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
