# Generated by Django 5.0.11 on 2025-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KienThuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='kien_thuc')),
                ('ngay_dang', models.DateField()),
            ],
        ),
    ]
