# Generated by Django 5.0.11 on 2025-01-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kienthuc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KienThuc',
            new_name='kien_thuc',
        ),
    ]
