# Generated by Django 5.0.11 on 2025-01-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kienthuc', '0002_rename_kienthuc_kien_thuc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kienthuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200)),
                ('noi_dung', models.TextField()),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='kien_thuc')),
                ('ngay_dang', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='kien_thuc',
        ),
    ]
